name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myco-exe
        path: bin/Release/net9.0/win-x64/publish/
        retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: myco-exe
        path: ./artifact

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifact/Myco.exe
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}